baseURL = "https://juliovega.info"
languageCode = "en-us"
title = "Julio Vega"
enableRobotsTXT = true

[blackfriday]
  plainIDAnchors = true
  hrefTargetBlank = true

[params]
  mainSections = ["blog", "news", "presentations", "projects", "publications"]

  [[params.reviews]]
  url = "https://dis.acm.org/2021/"
  name = "ACM DIS 2021"
  times = "1"

  [[params.reviews]]
  url = "https://chi2021.acm.org/"
  name = "ACM CHI 2021"
  times = "1"

  [[params.reviews]]
  url = "https://chi2020.acm.org/"
  name = "ACM CHI 2020"
  times = "1"

  [[params.reviews]]
  url = "https://www.springer.com/journal/779"
  name = "Personal and Ubiquitous Computing 2020"
  times = "1"

  [[params.reviews]]
  url = "https://chi2019.acm.org/"
  name = "ACM CHI 2019"
  times = "2"

  [[params.reviews]]
  url = "https://imwut.acm.org/"
  name = "ACM IMWUT 2018"
  times = "1"

  [[params.reviews]]
  url = "https://www.journals.elsevier.com/international-journal-of-human-computer-studies"
  name = "IJHCS 2017"
  times = "1"

  [[params.alumni]]
  name = "Team of 5-7 software engineers and data scientists"

  [[params.alumni]]
  name = "Undergraduate Capstone Course (HCI Program, CMU)"

  [[params.alumni]]
  name = "Huichuan Liu (MSc distinction)"

  [[params.alumni]]
  name = "Fanqi Meng (MSc)"

  [[params.alumni]]
  name = "Heng Zhang (MSc)"

  [[params.teaching]]
  url = "https://studentnet.cs.manchester.ac.uk/ugt/2014/COMP33512/syllabus/"
  name = "User Experience (UX)"
  times = "4"

  [[params.teaching]]
  url = "http://studentnet.cs.manchester.ac.uk/syllabus/?code=COMP16121"
  name = "Java I"
  times = "3"

  [[params.teaching]]
  url = "https://studentnet.cs.manchester.ac.uk/ugt/COMP16212/syllabus/"
  name = "Java II"
  times = "2"

  [[params.teaching]]
  url = "http://studentnet.cs.manchester.ac.uk/syllabus/?code=COMP38120&year=2016"
  name = "Documents, Services and Data on the Web"
  times = "1"

  [[params.teaching]]
  url = "http://studentnet.cs.manchester.ac.uk/syllabus/?code=COMP26120"
  name = "Algorithms and Imperative Programming"
  times = "1"
  

sectionPagesMenu = "main"
[menu]
    [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

    [[menu.main]]
    identifier = "news"
    name = "News"
    url = "/news/"
    weight = 3

    [[menu.main]]
    identifier = "publications"
    name = "Publications"
    url = "/publications/"
    weight = 4

    [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects/"
    weight = 5

    [[menu.main]]
    identifier = "presentations"
    name = "Presentations"
    url = "/presentations/"
    weight = 6

    [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "https://jvblog.net"
    weight = 7

    